name: Build and Push Docker Image

on:
  push:

permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: ghcr.io/canton-artifacts-dev/temp/hello

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: georgeorellanaDA
          password: ${{ secrets.CANTON_ARTIFACTS_DEV_PAC }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
